on:
  workflow_dispatch:
  schedule:
    - cron: "30 3,9,15,21 * * *"

jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: data-collection
      - name: Create Pull Request
        id: cpr
        run: gh pr create --base ${{ github.event.repository.default_branch }} --title "merge collected data" --body "merge collected data"
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Enable Pull Request Automerge
        run: gh pr merge --merge --auto ${{ steps.cpr.outputs.stdout }}
        env:
          GH_TOKEN: ${{ github.token }}
